embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
learning_rate: 0.001

reg_weight: [0.005, 0.01, 0.05, 0.1, 0.5]

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: [0.05, 0.1, 0.2, 0.3, 0.4]

mode: ['local']

hyper_parameters: ["dropout","reg_weight","mode"]